# Generated by Django 5.1.4 on 2025-03-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemDish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_id", models.IntegerField()),
                ("title", models.CharField(db_index=True, max_length=100)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("order_id", models.IntegerField()),
                ("table_number", models.IntegerField()),
                (
                    "items",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="orders.itemdish",
                    ),
                ),
                ("total_price", models.ImageField(blank=True, upload_to="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("В ожидании", "В ожидании"),
                            ("Готово", "Готово"),
                            ("Оплачено", "Оплачено"),
                        ],
                        default="В ожидании",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
